ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-log-warn
      - id: python-no-eval
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.47"
    hooks:
      - id: check-manifest
        stages: [manual]

    # Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

    # Terraform Linter
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
      - id: terraform_trivy
        files: ^terraform/

  # Dockerfile linter
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.1-beta
  hooks:
    - id: hadolint
      args: [
        '--ignore', 'DL3007', # Using latest
        '--ignore', 'DL3013', # Pin versions in pip
        '--ignore', 'DL3027', # Do not use apt
        '--ignore', 'DL3059', # Docker `RUN`s shouldn't be consolidated here
        '--ignore', 'DL4006', # Not related to alpine
        '--ignore', 'SC1091', # Useless check
        '--ignore', 'SC2015', # Useless check
        '--ignore', 'SC3037', # Not related to alpine
      ]